version: "3.9"
services:
  mqtt:
    build: mqtt_broker
    ports:
      - "1883:1883"
    restart: always
    networks:
      - backend
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
volumes:
  mosquitto_data:
  mosquitto_log:


networks:
  backend:
    driver: bridge

